In [137]:
### My implementaion of simple matrix multiplication (O(n^3))
function simple_matrix_multiplication(A::Matrix{T}, B::Matrix{T}) where T<:AbstractFloat
    n, m = size(A)
    m2, p = size(B)
    
    C = zeros(T, n, p)
    
    @inbounds @simd for i in 1:n
        @inbounds @simd for j in 1:p
            @inbounds @simd for k in 1:m
                C[i, j] += A[i, k] * B[k, j]
            end
        end
    end
    
    return C
end


simple_matrix_multiplication (generic function with 1 method)

In [162]:
### implementation of the sterassen matrix multiplication(O(n^2.83))
function strassen(A::Matrix{T}, B::Matrix{T}) where T<:AbstractFloat
    n = size(A, 1)

    if n <= 2
        return A * B
    else
        m = div(n, 2)

        # Partition the matrices into submatrices
        A11, A12 = A[1:m, 1:m], A[1:m, m+1:n]
        A21, A22 = A[m+1:n, 1:m], A[m+1:n, m+1:n]
        B11, B12 = B[1:m, 1:m], B[1:m, m+1:n]
        B21, B22 = B[m+1:n, 1:m], B[m+1:n, m+1:n]

        # Strassen's 7 products
        M1 = strassen(A11 + A22, B11 + B22)
        M2 = strassen(A21 + A22, B11)
        M3 = strassen(A11, B12 - B22)
        M4 = strassen(A22, B21 - B11)
        M5 = strassen(A11 + A12, B22)
        M6 = strassen(A21 - A11, B11 + B12)
        M7 = strassen(A12 - A22, B21 + B22)

        # Combining the results into the final matrix
        C11 = M1 + M4 - M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 - M2 + M3 + M6

        # Construct the final matrix from submatrices
        C = [C11 C12; C21 C22]
        return C
    end

    
end

strassen (generic function with 1 method)

In [115]:
### hybrid implementation of the sterassen, the matrices smaller than threshold we use normal multiplication \n",
function hybrid_strassen(A::Matrix{T}, B::Matrix{T}; threshold::Int = 64) where T<:AbstractFloat
    n = size(A, 1)

    if n <= threshold
        return A * B
    else
        m = div(n, 2)

        A11, A12 = A[1:m, 1:m], A[1:m, m+1:n]
        A21, A22 = A[m+1:n, 1:m], A[m+1:n, m+1:n]
        B11, B12 = B[1:m, 1:m], B[1:m, m+1:n]
        B21, B22 = B[m+1:n, 1:m], B[m+1:n, m+1:n]

        M1 = hybrid_strassen(A11 + A22, B11 + B22, threshold=threshold)
        M2 = hybrid_strassen(A21 + A22, B11, threshold=threshold)
        M3 = hybrid_strassen(A11, B12 - B22, threshold=threshold)
        M4 = hybrid_strassen(A22, B21 - B11, threshold=threshold)
        M5 = hybrid_strassen(A11 + A12, B22, threshold=threshold)
        M6 = hybrid_strassen(A21 - A11, B11 + B12, threshold=threshold)
        M7 = hybrid_strassen(A12 - A22, B21 + B22, threshold=threshold)

        C11 = M1 + M4 - M5 + M7
        C12 = M3 + M5
        C21 = M2 + M4
        C22 = M1 - M2 + M3 + M6

        return [C11 C12; C21 C22]
    end
end

hybrid_strassen (generic function with 1 method)

In [157]:
# implementation of the GPU-accelerated hybrid Strassen function
    function hybrid_strassen_gpu(A::Matrix{T}, B::Matrix{T}; threshold::Int = 64) where T<:AbstractFloat
        n = size(A, 1)
    
        # Base case: Use standard multiplication on the GPU for small matrices
        if n <= threshold
            A_gpu = CuArray(A)
            B_gpu = CuArray(B)
            return A_gpu * B_gpu
        else
            m = div(n, 2)
    
            # Partition the matrices into submatrices
            A11, A12 = A[1:m, 1:m], A[1:m, m+1:n]
            A21, A22 = A[m+1:n, 1:m], A[m+1:n, m+1:n]
            B11, B12 = B[1:m, 1:m], B[1:m, m+1:n]
            B21, B22 = B[m+1:n, 1:m], B[m+1:n, m+1:n]
    
            # Recursively calculate the 7 products using hybrid Strassen's method
            M1 = hybrid_strassen_gpu(A11 + A22, B11 + B22, threshold=threshold)
            M2 = hybrid_strassen_gpu(A21 + A22, B11, threshold=threshold)
            M3 = hybrid_strassen_gpu(A11, B12 - B22, threshold=threshold)
            M4 = hybrid_strassen_gpu(A22, B21 - B11, threshold=threshold)
            M5 = hybrid_strassen_gpu(A11 + A12, B22, threshold=threshold)
            M6 = hybrid_strassen_gpu(A21 - A11, B11 + B12, threshold=threshold)
            M7 = hybrid_strassen_gpu(A12 - A22, B21 + B22, threshold=threshold)
    
            # Combining the results into the final matrix
            C11 = M1 + M4 - M5 + M7
            C12 = M3 + M5
            C21 = M2 + M4
            C22 = M1 - M2 + M3 + M6
    
            # Combine the results into a full matrix
            C = vcat(hcat(C11, C12), hcat(C21, C22))
    
            return C
        end
    end

hybrid_strassen_gpu (generic function with 1 method)

In [5]:
#padding the matrix to make it n*n where n=2^k, this is the only suitable size for Strassen algorithm
function pad_matrix(M1::Matrix{T}, M2::Matrix{T} ) where T<:AbstractFloat
    n=2^ceil(Int, log2(max(size(M1)[1], size(M1)[2], size(M2)[2])))
    padded_M1 = zeros(T, n, n)
    original_size = size(M1)
    padded_M1[1:original_size[1], 1:original_size[2]] = M1

    padded_M2 = zeros(T, n, n)
    original_size = size(M2)
    padded_M2[1:original_size[1], 1:original_size[2]] = M2

    return padded_M1, padded_M2
end

pad_matrix (generic function with 1 method)

In [133]:
#example A and B for multipllication
n = 4
m=4
k=4
A = rand(Float32, n, m);
B = rand(Float32, m, k);

In [138]:
@time C = simple_matrix_multiplication(A, B)

  0.043663 seconds (18.64 k allocations: 1.236 MiB, 99.90% compilation time)


4×4 Matrix{Float32}:
 0.835684  0.651034  0.202926  0.742347
 1.20989   1.01573   0.394657  1.01885
 0.335738  0.318568  0.119275  0.363165
 0.954904  1.14983   1.01012   0.933305

In [163]:
padded_A, padded_B = pad_matrix(A, B)
@time C_padded = strassen(padded_A, padded_B)
C1 = C_padded[1:size(A)[1], 1:size(B)[2]]

  0.047477 seconds (22.95 k allocations: 1.307 MiB, 99.90% compilation time)


4×4 Matrix{Float32}:
 0.835684  0.651034  0.202926  0.742346
 1.20989   1.01573   0.394657  1.01885
 0.335738  0.318568  0.119275  0.363165
 0.954904  1.14983   1.01012   0.933305

In [139]:
padded_A, padded_B = pad_matrix(A, B)
@time C_padded = hybrid_strassen(padded_A, padded_B)
C2 = C_padded[1:size(A)[1], 1:size(B)[2]]

  0.000010 seconds (1 allocation: 128 bytes)


4×4 Matrix{Float32}:
 0.835684  0.651034  0.202926  0.742346
 1.20989   1.01573   0.394657  1.01885
 0.335738  0.318568  0.119275  0.363165
 0.954904  1.14983   1.01012   0.933305

In [161]:
@time C_padded = hybrid_strassen_gpu(padded_A, padded_B)
C3 = C_padded[1:size(A)[1], 1:size(B)[2]]
C3=Array(C3)

  0.539819 seconds (65 allocations: 1.656 KiB)


4×4 Matrix{Float32}:
 0.835684  0.651034  0.202926  0.742347
 1.20989   1.01573   0.394657  1.01885
 0.335738  0.318568  0.119275  0.363165
 0.954904  1.14983   1.01012   0.933305

In [142]:
@time C4=A*B

  0.000035 seconds (1 allocation: 128 bytes)


4×4 Matrix{Float32}:
 0.835684  0.651034  0.202926  0.742346
 1.20989   1.01573   0.394657  1.01885
 0.335738  0.318568  0.119275  0.363165
 0.954904  1.14983   1.01012   0.933305

In [164]:
isapprox(C4, C1)

true